---
title: "Understanding the variability in macromolecular composition of soil microbial biomass"
author: "Petr Čapek, Michal Choma, Eva Kaštovská, Karolina Tahovská, Helen Glanville, Hana Šantrůčková"
date: "`r Sys.Date()`"
output: word_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction

Macromolecular and elemental composition of cells of single-species microbial communities is known to vary significantly [@Hanegraaf2001; @Makino2003; @herbert1961]. As quoted by Denis Herbert, "Such a statement as 'the ribonucleic acid content of Bacillus cereus is 16.2%' is by itself as incomplete and misleading as the statement 'the boiling-point of water is 70°C'.". Variability in cell composition is primarily associated with changes in specific growth rate (Fig. 1A, @Hanegraaf2001; @Herbert1961; @Makino2003). To grow as fast as possible, microbial cells require several macromolecules and metabolites with unique elemental composition [@Vrede2004; @Franklin2011] that transforms consumed substrates into various cell components. Typical example of macromolecule mediating growth is ribosomal RNA, which performs translation of genetic code into a sequence of amino acids. Because the rate of translation per unit of one ribosome is constant, increase in growth rate can be achieved only by increasing the ribosomal RNA content [@Vrede2004; @Franklin2011]. For that reason, ribosomal RNA content typically increases with increasing specific growth rate (Fig. 1A, @Hanegraaf2001; @Makino2003; @Herbert1961).

To describe the relationship between the growth rate and cell composition, it proved convenient to distinguish at least two pools of microbial biomass (Fig. 1C, @Hanegraaf2001; @Franklin2011). One pool represents all cell constituents that are present in non-growing cell. The second pool represents the macromolecules and metabolites that are associated with increased specific growth rate [@Hanegraaf2001; @Franklin2011]. The terminology is not unified in respect to these pools because they are abstract. [@Hanegraaf2001] for example, denote them as "Structures" and "Reserves", respectively. [@Franklin2011] use the terms "baseline biomass" and "growth machinery" (authors also distinguish the third pool of "uptake machinery"). For convenience, we will hereafter use the terms "Basal biomass" ($B$) and "Growth intermediates" ($G$). As the $G$ increases, specific growth rate increases accordingly (see section 2.1. for detail description). Defining the macromolecular content and/or elemental stoichiometry of pools $B$ and $G$ allows then to associate changes in cell composition directly to changes in specific growth rate (Fig. 1A; @Hanegraaf2001; @Hanegraaf2000). In other words, the pools $B$ and $G$ represent a reliable simplification of otherwise complex microbial physiology.

Soil microbial communities are characteristic by co-occurrence of many species in the same microenvironments. Given the fact that different species might have different characteristics such as basal DNA or RNA content, it remains unclear if any generalizable relationship between the specific growth rate and composition of soil microbial biomass can exist. Several empirical evidences suggest that it can. By tracking the radiolabelled glucose added to soil at different concentrations, @bremer1990 found that two pools of soil microbial biomass should be distinguished to explain variability in chloroform-labile content of microbial biomass, i.e. the $k_{ec}$ factor. The similar conclusion was later on reached by @glanville2016. Other studies showed that the ratio between chloroform-labile organic carbon (CLC) and various macromolecules (i.e. DNA @Marstorp1999; @malik2015, ATP @tsai1997; @joergensen2002, RNA and PLFA @malik2015; @gunina2017) changes significantly and consistently over time or across organic substrate (typically glucose) concentrations. @tessier1998 found a consistent relationship between the total soil organic carbon (C) content, which affects the growth rate of microbial biomass, and the $k_{ec}$ factor. Recently, @hagerty2022 showed that considering two pools of soil microbial biomass significantly improves a simulation accuracy of microbially-explicit mathematical models.

If the generalizable relationship between the microbial biomass composition and the specific-growth rate can be defined for soil microbial communities, it would have four important implications that are intimately linked. The first two implications are methodological. *(i)* Understanding the relationship between the microbial biomass composition and the specific growth rate can improve the quantification of the total soil microbial biomass. Most of the methods relies on quantitative extraction of some part of microbial biomass, so called biomass proxy parameter (e.g. CLC @Vance1987, DNA @Marstorp1999, PLFA @ziegler2005, ATP @blagodatskaya2013). Total microbial biomass is then calculated as a product of the proxy parameter and arbitrary defined conversion factor, which is, in many cases, assumed to be invariant even though the empirical results prove the opposite. For example, the $k_{ec}$ factor changes significantly over the course of few days after organic substrate addition [@glanville2016; @bremer1990; @santruckova2004] and may vary by a factor of up to 30 among different soils or soil depths [@sparling1989; @sparling1988; @Dictor1998]. The specific growth rate could explain at least part of this variability [@tessier1998; @bremer1990]. *(ii)* Improved quantification of total soil microbial biomass improves the calculation of biomass-specific physiological parameters, such as carbon use efficiency [@geyer2019; @hagerty2022] and turnover rate [@chen2019], which are based on the flux analysis of the isotopically labelled substrates through the total microbial biomass. *(iii)* When two commonly measured biomass proxies show consistently distinct relationship to specific growth rate, their ratio can be used as a simple indicator of the growth rate. (iv) At last, improved mechanistic and quantitative understanding of soil microbial community physiology may improve the simulation accuracy of microbially-explicit soil biogeochemical models even above the level calculated by [@hagerty2022], whose analysis sticks to the assumption of constant composition of soil microbial biomass.

The aim of this study is to define the relationship between the macromolecular composition of soil microbial biomass, and to determine its validity and generalizability. To do so, we first attempt to explain the temporal variability in $k_{ec}$ factor and ratios between different macromolecules individually as reported in previously published studies. We use a microbially-explicit mathematical model inspired by the Dynamic Energy Budget theory [@Hanegraaf2001; @kooijman1991; @Kooijman2009]. Then, we use this model to explain the variability in all data products across all published studies using one set of model parameters. We hypothesize that defining the two pools of soil microbial biomass and their macromolecular content can explain the variability in $k_{ec}$ factor and ratios of different macromolecules within and across different soils.

## 2. Material and Methods

### 2.1. Theory

#### 2.1.1. Mathematical model

Here we present a theoretical background and formulation of a mathematical model, which is inspired by the Dynamic Energy Budget theory [@Hanegraaf2001; @kooijman1991; @Kooijman2009] and is used to explain variability in macromolecular composition of soil microbial biomass. The mathematical formulation is, however, defined directly on per C-1 molar basis to avoid excessive number of conversion factors, and the terminology common to soil microbial studies is used. For simplicity, we assume that the microbial community is composed of heterotrophic microorganisms, volume and shape of all microbial cells do not change over time and it is similar across soils, the aerobic conditions dominate in all microenvironments, the catabolic reactions within the cell degrades organic substrate completely to $CO_{2}$ (i.e. release of fermentation products to soil is negligible), and the extracellular enzymes production is negligible.

The model is schematically shown on Fig. 1C (see also Tab. 1 for list of symbols and their explanation) and recognizes four different carbon pools - organic substrate ($S$), $B$, $G$, and $CO_{2}$. Total microbial biomass ($MB$) is a sum of $B$ and $B \times G$ because $G$ is scaled to $B$ (i.e. growth intermediates are located inside the cell). $S$ is the entire source of energy and C for microbial biomass. Its uptake rate ($U$) is proportional to $B$ (i.e. $G$ has no effect) and follows classical hyperbolic scaling with $S$:

$U = I_m \times B \times f;~~~f = \frac{S}{K_m + S}.$ (1)

In eq. 1, $I_m$ is maximum uptake rate of a substrate and $K_M$ is half-saturation constant. $S$ taken up gets assimilated, i.e. converted to $G$. There are overhead energy costs of assimilation resulting in production of $CO_{2}$ (Fig. 1C, assimilatory respiration). It is assumed that these costs are covered directly from $S$. Substrate assimilation ($A$) and assimilatory respiration ($R_{assimilatory}$) rates are respectively defined as:

$A = U \times y_A,$ (2)

and

$R_{assimilatory} = U \times (1-y_A).$ (3)

In eqs. 2 and 3, $y_A$ defines the efficiency of substrate conversion into $G$. Once the $S$ is assimilated, $G$ can be mobilized and used to either cover maintenance costs or/and to grow (i.e. produce $B$). The mobilization rate of $G$($J$) is defined as:

$J = A_m \times \frac{G}{G_M}.$ (4)

In eq. 4, $A_m$ is specific maximum assimilation rate constant, which is equal to $I_m \times y_A$. $G_m$ is maximum content of $G$ that the cell can have. Thus, the more substrate the cell assimilates into growth intermediates, the faster the $G$ can be mobilized. $G$ content cannot exceed $G_m$, so $\frac{G}{G_m}$ is always a number between 0 and 1. When $\frac{G}{G_m}$ is 1, $J$ reaches the maximum under the given environmental conditions.

At any time, microbial cell has to maintain integrity of its basal cellular material $B$, $G$ requires no maintenance. Cellular integrity maintenance is associated with $CO_{2}$ production because it requires energy (Fig. 1C, maintenance respiration). The maintenance respiration ($R_{maintenance}$) is defined as:

$R_{maintenance} = m \times B.$ (5)

In eq. 5, $m$ is the specific maintenance rate coefficient.

If the amount of $G$ is sufficiently high (see the details below), microbial biomass can grow. Growth is simply defined as a change of $B$ over time ($\frac{dB}{dt}$). Because the growth is defined as a conversion of $G$ to $B$, it is associated with energy costs (Fig. 1C, growth respiration) and thus, growth respiration ($R_{growth}$) defined by eq. 6:

$R_{growth} = g \times \frac{dB}{dt},$ (6)

in which $g$ defines the energy cost of growth in terms of amount of $CO_{2}$ produced per unit of produced $B$.

Maintenance of cellular integrity has an absolute priority over growth. Thus, growth is realized only if $J$ is higher than $m$. Fluxes $R_{maintenance}$, $R_{growth}$ and $\frac{dB}{dt}$ balance change of $G$ over time:

$\underbrace{m \times B}_{R_{maintenance}} + \underbrace{g \times \frac{dB}{dt}}_{R_{growth}} + \underbrace{\frac{dB}{dt}}_{growth} = \underbrace{J \times B}_{G~mobilization~rate~within~cells}  - \underbrace{\frac{dB}{dt} \times G}_{dilution~of~G~by~growth}.$ (7)

The second term on the right hand side of eq. 7 defines the dilution of pool $G$ by the growth. Because $G$ is scaled to $B$, an increase of pool $B$ decreases $G$. Without that term, the mass balance would be violated. Eq. 7 can be rearranged to find a formulation of $\frac{dB}{dt}$, which is defined by the equation 8

$\frac{dB}{dt} = \mu \times B;~~\mu = \frac{J-m}{1+g+G}.$ (8)

Eq. 8 shows that the specific growth rate ($\mu$) as a function of $J$, $m$, $g$ and $G$ - a variables, which are all scaled to pool $B$ (i.e. biomass specific). It also shows that $\mu$ is positive when the amount of $G$ is high enough to produce flux $J$ exceeding $m$. In opposite case, $\mu$ becomes negative. If $G$ is so small that it cannot cover the maintenance costs, these costs must be covered from $B$. The eq. 8, however, must be rearranged to:

$\frac{dB}{dt} = \mu \times B \times (1+g).$ (9)

because $\mu$ simplifies to $m$ when $G$ is zero and the eq. 9 becomes equivalent to eq. 5. This formulation aligns well with the empirical observations. In nature, the microbial cells may temporarily maintain its basal metabolism to survive the starvation period when growth ceases. During this time, the cell shrinks (and/or changes shape) because all maintenance C costs are met from the pool of basal cellular material (i.e. depolymerized cellular structures, @mason1993). The period of basal metabolism maintenance can last up to several months in some cases [@morita1993].

To summarize the theoretical background, the mathematical model depicted on Fig. 1C is described by four differential equations defined respectively for pools $S$, $G$, $B$, and $CO_2$ as follows:

$\frac{dS}{dt} = -U,$ (10)

$\frac{dG}{dt} = A_m \times (f-\frac{G}{G_m}),$ (11)

$\frac{dB}{dt} = \left\{ \begin{array}{rcl}\mu \times B & \mbox{for}& \mu \geq 0 \\\ \mu \times B \times (1+g) & \mbox{for} & \mu < 0\end{array}\right.,$ (12)

$\frac{dCO_2}{dt} = R_{assimilatory} + R_{maintenance}+min(R_{growth}, 0).$ (13)

The last term of eq. 13 ($min(R_{growth}, 0)$) means that the growth respiration occurs only when growth is realized ($\mu$ is positive).

#### 2.1.2. Conversion factors

## References:
